# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

# Main Page Setup

title: Johnathan Machler Portfolio # This is what shows up in the tab of the browser



# Hero Section
name: Johnathan Machler
headline: Engineer | Researcher | Nexialist
description:  I am passionate about systems thinking and always strive to find holistic solutions where applicable. This passion dates back to childhood when I started with snap circuits, read vintage electronics manuals, and visited RadioShack on my days off. On Fridays, I visited my mentor, a chief engineer and inventor, who taught me the mentality and dedication of an engineer. He didn't see a separation between his work as a scientist and his faith.
Disenfranchised with the modern world, I recently adopted a more ascetic lifestyle, purchasing only what I need when I need it. In December 2024, I converted to Orthodox Christianity and dedicated more of my life to it. I overcame many earthy and carnal temptations within myself.
I am actively improving and preparing to launch several projects, part of my larger talent stack. In June 2024, I started Machlerlabs.com and Machler Labs LLC with the intention of reinventing how toys are made, adapting IDEO and MIT Media Lab research to product and app design. The vision is to find new ways to integrate AI into toys through electronics or handheld phones. Before starting this business, I worked for Raytheon Missile Systems, but it didn't work out for unknown reasons. This company can be seen as a reuse of high tech skills to the toy industry, which needs reinvigoration in the area of kids staring at glowing rectangles. Let's get kids off their phones or, if not, get them to use phones with their toys. Essentially I see myself going up against Mattel and the creators of Pokemon Go. What is seen now in the toy industry is full of bloat. I feel that the media study, be it toys or movies, is uninspired.
With the spare time I have, I scour YouTube, the library, and other free resources for information on various disciplines. My knowledge ranges from Electrophysiology to word origin Etymology (to see the actual list of interests I have along with the markdown study notes see this link). I pride myself on being able to speak intelligently on almost any topic I desire. You can watch my podcasts here at this link. 

# Place your profile image in /assets/images/profile-image/folder and edit the file name
profile_image: ./assets/images/profile-image/avatar.jpeg


# Link your resume
# You can place your resume in assets/resume/{resume file.pdf} or add external link such as pdf saved in google drive 
resume-url: https://machler.xyz/resume/JmachlerResume-2-1.pdf


# Set up external links - this will show up as small icons next to your name.

external-links:    # input only your own url slug. The icons with missing entries will not appear.
  linkedin: test    # https://www.linkedin.com/in/{your url slug} 
  github: jmachl    # https://github.com/{your url slug} 
  stackoverflow: test      # https://stackoverflow.com/users/{your url slug}
  medium:            # https://medium.com/@{your url slug} 
  x-twitter:   # https://x.com/{your url slug} 
  threads:            # https://threads.net/@{your url slug} 
  instragram:       # https://instagram.com/{your url slug} 
  youtube: kd0moo           # https://youtube.com/@{your url slug} 
  discord:            # https://discord.com/users/{your url slug} 
  bluesky:           # https://bsky.app/profile/{your url slug} 
  

# Skills Section - Add the list of your Skills by categories/tools. The indentation for each level needs to be precise. 
skills:

  - category: Programming Languages
    tools:
    - C++/C
    - MATLAB
    - VHDL
    - Python

  - category: 3D Modeling
    tools:
    - Onshape
    - Solidworks
    - Fusion 360 (Autodesk)
    - Blender (for complex shapes or animations)

    
  - category: Prototyping
    tools:
    - SLA
    - CNC
    - FDM
    - SLS
    - DMLS
    - PolyJet Printing
    - Vacuum Casting
    - Laser Cutting
    - Arduino / Raspberry Pi, STM32
    - Breadboarding for circuit testing
    
  - category: PCB Design
    tools:
    - Altium Designer 
    - KiCad
    - EasyEDA
    - Eagle
    
  - category: Modeling and Simulation
    tools:
    - Simulink
    - Cadence
    - NGSPICE
    - LtSpice
    - Modelsim

   - category: Documentation
    tools:
    - Microsoft Suites
    - Juypter Notebooks
    - Roam Research
    - Obsidian

   - category: Version Control
    tools:
    - Windchill 
    - Git
    - Jira /Confluence
    - Subversion
 
  


# Contact Form Setup. Setup an account and copy over the key. When someone fills out the form, it will be received in your email.
formspree-key:   https://formspree.io/f/{8-digit key}



# Active theme (Updatethis to switch themes). Make sure to keep the indentation the samne.
colors: # this is the basic theme
  text: "#1a1c20"
  border: "#ddd"
  link: "#4a76ee"
  highlight: "#0c0cf2"
  background: "#ffffff"
  light_background: "#f3f5fb"

# A few examples. 
basic theme:
  text: "#1a1c20"
  border: "#ddd"
  link: "#4a76ee"
  highlight: "#0c0cf2"
  background: "#ffffff"
  light_background: "#f3f5fb"
  
  mint theme:
  text: "#2c3333"
  border: "#e0f2ef"
  link: "#40b3a2"
  highlight: "#2a9d8f"
  background: "#f7fbfa"
  light_background: "#f0f9f7"
  
lemon theme:
  text: "#2d2926"
  border: "#f7f3e3"
  link: "#ffc94d"
  highlight: "#ffb800"
  background: "#fffdf5"
  light_background: "#fff9e6"
  
  pink theme:
  text: "#2d2d2d"
  border: "#f8e2e2"
  link: "#ff8fa3"
  highlight: "#ff4d6d"
  background: "#fff8f8"
  light_background: "#fff5f6"






#########################################################################################################
# Build settings for the site. Editing the below may cause the site to malfunction.

collections:
  projects:
    output: true
    permalink: /projects/:path/


markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
      indent: 0

plugins:
  - jekyll-feed

include:
  - _projects


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
